name: MD-Checks

on: [push, pull_request]

jobs:
  lint-changelog:
    name: Lint changelog file
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Markdown Linting Action
        uses: avto-dev/markdown-lint@v1.5.0
        with:
          args: "*.md"
